### ISSUE TITLE
Review comments: 2.7 ClassDefinitionEvaluation

### ISSUE THREAD

**Issue by ajklein** [tc39/proposal-private-methods#14]
This is my first time doing formal review of a sizable spec; let me know if there's a better workflow I should use than just filing issues. I'm currently reading through ClassDefinitionEvaluation, and the below is a variety of issues I found:

1. When invoking `ClassElementEvaluation`. step 27.c passes `true` for `enumerable`. I believe this should be `false`.

1. Step 28 reads: "Let _elements_ be _elements_ with getters and setters of the same key coalesced, with later declarations overriding earlier ones." I think I understand what you mean by "coalesced" (though I think this could be improved by spelling it out), but I don't understand the second part of the sentence ("with later declarations..."), since there should be at most one getter and one setter for a given key, and the two should have all the same descriptor attributes save `[[Get]]` and `[[Set]]`.

1. Can the invocation of `InitializeClassElements` at step 33 fail? I'm having trouble seeing how, yet I see a `?` preceding it. I'm likely missing something though.

1. While on the topic of `InitializeClassElements`, the Assert in step 3 says "proto is F.[[Prototype]]", but presumably you mean that proto is identical to `Get(F, "prototype")`?

**Comment by littledan** [comment]
3. InitializeClassElements can throw if a static field initializer throws an exception, from the Call in DefineClassElement.

Thanks for the other issues; fixes coming soon.
