### ISSUE TITLE
Are private own methods also defined on the prototype?

### ISSUE THREAD

**Issue by nicolo-ribaudo** [tc39/proposal-private-methods#29]
InitializeClassElements step 5.b defines the classes' methods as follows:
- If their `placement` is `"static"`, they are defined on the class
- Otherwise (if their `placement` is `"prototype"` or `"own"`) they are defined on the prototype.

Private methods on the prototype are probably not observable, but using decorators someone could define a public own method: should it be defined only on the instance or also on the prototype?

**Comment by littledan** [comment]
Private methods on the prototype would be observable. I didn't mean for this proposal to include them, but it looks like there is an error in the specification text and they are currently included. Seems like we need a check in https://tc39.github.io/proposal-private-methods/#initialize-class-elements 5.b similar to the check in 6.a. Would you be interested in making a specification patch to fix the issue?

For example, this code should throw a TypeError when looking up `#z` within `y()`:

```js
class X {
  y() { this.#z(); }
  #z() { }
}
X.prototype.y()
```
