### ISSUE TITLE
Should private methods be auto-bound?

### ISSUE THREAD

**Issue by littledan** [tc39/proposal-private-methods#5]
We "missed our chance" with public methods, but auto-bound methods are a big feature request. Should we make private methods auto-bound? This was suggested [on Twitter by codemix](https://twitter.com/codemixers/status/880464424355627010), though @thejameskyle noted there,

> That's overhead for instantiation and it breaks the pattern already set up. Performance and consistency are valuable

I wasn't there for the ES6 class discussion; do the arguments made there against auto-bound methods apply equally to private methods? cc @arv @dslomov

**Comment by arv** [comment]
It all depends on the semantics... I always imagined these more like funtions in the class scope but at this point I'm not sure what the plan is?

**Comment by littledan** [comment]
With a patch I landed today, they'd be similar to that, except that if the receiver isn't an instance, they'd throw a TypeError. Mechanically, they are like a private field which is non-writable, and the same for all instances. What would you think of that?

**Comment by arv** [comment]
So at the moment the semantics is the same a private property which happens to be a function?

Intuitively automatically binding these should be cheaper than Function.prototype.bind since it is a special more limited case.

However, I'm not sure this is the right semantics and whether it is worth the exception.

**Comment by littledan** [comment]
OK, we're not going to make private methods auto-bound.
