### ISSUE TITLE
Update progress of Babel Implementation

### ISSUE THREAD

**Issue by tim-mc** [tc39/proposal-private-methods#53]
The link to my private methods babel PR in the README under ["Implementations"](https://github.com/tc39/proposal-private-methods/blob/59bcc6ac0805f323d1d9a2fba34a25f7dbf84fae/README.md#implementations) states that it is in progress. The PR has now been merged, and there's [another one now open for private accessors](https://github.com/babel/babel/pull/9101). Should this be updated either with the new PR or with slightly different text (or both)?

**Comment by littledan** [comment]
Great, PRs welcome!

**Comment by tim-mc** [comment]
Fixed by #54
