### ISSUE TITLE
Accessible from a super class?

### ISSUE THREAD

**Issue by stevenvachon** [tc39/proposal-private-methods#68]
```js
class A {
  #prop = 'value';
}

class B extends A {
  constructor() {
    console.log(this.#prop); //-> ??
  }
}
```

**Comment by bakkot** [comment]
That gives a syntax error. Fields are only accessible within the class which defines them.

**Comment by stevenvachon** [comment]
Thanks. Is there a spec somewhere that describes this?

**Comment by bakkot** [comment]
Yes, [here](https://tc39.es/proposal-class-fields/#sec-static-semantics-early-errors). There's also [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#Field_declarations).
