### ISSUE TITLE
How syntax consensus has been formed over private elements?

### ISSUE THREAD

**Issue by konstardiy** [tc39/proposal-private-methods#74]
I see that the `#` syntax is come to phase 3.
I want to get a general understanding of this quite unusual decision of syntax, especially since there is a common tradition across languages about this, by using `private` keyword. JS has a long-term practice which supported by many IDEs to support `_name` format and treat these fields as sort of  prvate and do not suggest them in code completion outside of logical scope visiblity.

What caused to peek the special, "shebang-like" syntax?

**Comment by slikts** [comment]
[FAQ](https://github.com/tc39/proposal-private-fields/blob/master/FAQ.md).
